#!/usr/bin/env node
/**
 * dataimago Design System Build Script
 * 
 * Compiles design tokens and SCSS into production-ready CSS assets.
 * This build script is called by R functions in design_system.R to maintain
 * the "R as source of truth" philosophy while leveraging Node.js tooling.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Configuration
const config = {
  srcDir: path.join(__dirname, 'src'),
  distDir: path.join(__dirname, 'dist'),
  tokensDir: path.join(__dirname, 'src', 'tokens'),
  stylesDir: path.join(__dirname, 'src', 'styles')
};

console.log('🛠️  dataimago: Building design system assets...');

// Step 1: Process design tokens with Style Dictionary
console.log('📋 Processing design tokens...');

// Style Dictionary configuration
const styleDictionaryConfig = {
  source: [path.join(config.tokensDir, '**/*.json')],
  platforms: {
    css: {
      transforms: [
        'attribute/cti',
        'name/kebab', 
        'time/seconds',
        'size/rem',
        'color/hex'
      ],
      buildPath: config.distDir + '/',
      files: [{
        destination: 'tokens.css',
        format: 'css/variables',
        options: {
          selector: ':root',
          outputReferences: true
        }
      }]
    }
  }
};

// Write temporary Style Dictionary config
const configPath = path.join(__dirname, 'style-dictionary-temp.json');
fs.writeFileSync(configPath, JSON.stringify(styleDictionaryConfig, null, 2));

try {
  // Run Style Dictionary
  execSync(`npx style-dictionary build --config ${configPath}`, { 
    stdio: 'inherit',
    cwd: __dirname 
  });
  console.log('✅ Design tokens processed successfully');
} catch (error) {
  console.error('❌ Style Dictionary build failed:', error.message);
  process.exit(1);
} finally {
  // Clean up temporary config
  if (fs.existsSync(configPath)) {
    fs.unlinkSync(configPath);
  }
}

// Step 2: Create main SCSS file that imports everything
const mainScssContent = `
// dataimago Design System - Main Entry Point
// Generated by build.js - do not edit directly

// Import design tokens (CSS custom properties)
@import '../dist/tokens.css';

// Base styles using design tokens  
@import 'styles/base';
@import 'styles/components';
@import 'styles/utilities';
@import 'styles/accessibility';
`;

const mainScssPath = path.join(config.srcDir, 'main.scss');
fs.writeFileSync(mainScssPath, mainScssContent);

// Step 3: Compile SCSS to CSS
console.log('🎨 Compiling SCSS...');

try {
  const sassCmd = `npx sass ${mainScssPath}:${path.join(config.distDir, 'dataimago.css')} --style=expanded --source-map`;
  execSync(sassCmd, { stdio: 'inherit', cwd: __dirname });
  console.log('✅ SCSS compiled successfully');
} catch (error) {
  console.error('❌ SCSS compilation failed:', error.message);
  process.exit(1);
}

// Step 4: Run PostCSS for optimization
console.log('⚡ Running PostCSS optimization...');

// PostCSS configuration
const postcssConfig = {
  plugins: [
    require('autoprefixer'),
    require('cssnano')({
      preset: 'default'
    })
  ]
};

try {
  const postcssConfigPath = path.join(__dirname, 'postcss.config.js');
  fs.writeFileSync(postcssConfigPath, `module.exports = ${JSON.stringify(postcssConfig, null, 2)};`);
  
  const postcssCmd = `npx postcss ${path.join(config.distDir, 'dataimago.css')} -o ${path.join(config.distDir, 'dataimago.min.css')} --config ${postcssConfigPath}`;
  execSync(postcssCmd, { stdio: 'inherit', cwd: __dirname });
  
  console.log('✅ PostCSS optimization complete');
  
  // Clean up PostCSS config
  if (fs.existsSync(postcssConfigPath)) {
    fs.unlinkSync(postcssConfigPath);
  }
} catch (error) {
  console.error('❌ PostCSS optimization failed:', error.message);
  process.exit(1);
}

// Step 5: Generate Tailwind preset for Next.js integration
console.log('🌊 Generating Tailwind preset...');

const tailwindPreset = `
// dataimago Tailwind CSS Preset
// Generated by build.js - enables dataimago design system in Next.js apps

module.exports = {
  theme: {
    extend: {
      colors: {
        'di-primary': 'var(--color-brand-primary, #2C3E50)',
        'di-secondary': 'var(--color-brand-secondary, #34495E)', 
        'di-accent': 'var(--color-brand-accent, #3498DB)',
        'di-ethical': 'var(--color-brand-ethical, #E74C3C)'
      }
    }
  }
};
`;

fs.writeFileSync(path.join(config.distDir, 'tailwind-preset.js'), tailwindPreset);
console.log('✅ Tailwind preset generated');

// Step 6: Generate build manifest
const manifest = {
  name: 'dataimago Design System',
  version: '0.1.0', 
  buildTime: new Date().toISOString(),
  assets: {
    'tokens.css': 'CSS custom properties from design tokens',
    'dataimago.css': 'Expanded CSS for development',
    'dataimago.min.css': 'Minified CSS for production',
    'tailwind-preset.js': 'Tailwind CSS preset for Next.js integration'
  }
};

fs.writeFileSync(
  path.join(config.distDir, 'manifest.json'), 
  JSON.stringify(manifest, null, 2)
);

// Clean up temporary files
if (fs.existsSync(mainScssPath)) {
  fs.unlinkSync(mainScssPath);
}

console.log('🎉 dataimago design system build complete!');
console.log(`📁 Assets generated in ${config.distDir}/`);

// List generated files
const files = fs.readdirSync(config.distDir);
files.forEach(file => {
  const filePath = path.join(config.distDir, file);
  const stats = fs.statSync(filePath);
  const sizeKB = Math.round(stats.size / 1024 * 100) / 100;
  console.log(`   ✓ ${file} (${sizeKB} KB)`);
});

console.log('🧠 Ethical AI design system ready for deployment!');