#!/usr/bin/env node
/**
 * dataimago Design System Build Script
 * 
 * Compiles design tokens and SCSS into production-ready CSS assets.
 * This build script is called by R functions in design_system.R to maintain
 * the "R as source of truth" philosophy while leveraging Node.js tooling.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Configuration
const config = {
  srcDir: path.join(__dirname, 'src'),
  distDir: path.join(__dirname, 'dist'),
  tokensDir: path.join(__dirname, 'src', 'tokens'),
  stylesDir: path.join(__dirname, 'src', 'styles'),
  jsDir: path.join(__dirname, 'src', 'js')
};

console.log('🛠️  dataimago: Building design system assets...');

// Step 1: Process design tokens with Style Dictionary
console.log('📋 Processing design tokens...');

// Enhanced Style Dictionary configuration with theme support
const styleDictionaryConfig = {
  source: [path.join(config.tokensDir, '**/*.json')],
  platforms: {
    css: {
      transforms: [
        'attribute/cti',
        'name/kebab', 
        'time/seconds',
        'size/rem',
        'color/hex'
      ],
      buildPath: config.distDir + '/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/theme-variables', // Custom format for theme-aware variables
          options: {
            selector: ':root',
            outputReferences: true
          }
        },
        {
          destination: 'tokens-flat.css', // Fallback flat variables
          format: 'css/variables',
          options: {
            selector: ':root',
            outputReferences: true
          }
        }
      ]
    }
  }
};

// Process theme-aware tokens manually (custom implementation)
console.log('🎨 Processing theme-aware tokens...');

function processThemeTokens() {
  const tokenFiles = ['colors.json', 'theme-colors.json', 'frequent.json', 'effects.json', 'components.json', 'typography.json'];
  let cssContent = ':root {\n';
  let themeCssContent = '';
  
  // Light theme variables
  let lightThemeContent = ':root, [data-bs-theme="light"] {\n';
  
  // Dark theme variables  
  let darkThemeContent = '[data-bs-theme="dark"] {\n';
  
  // Media query for automatic dark mode
  let mediaQueryContent = '@media (prefers-color-scheme: dark) {\n  :root {\n';
  
  tokenFiles.forEach(filename => {
    const filepath = path.join(config.tokensDir, filename);
    if (!fs.existsSync(filepath)) return;
    
    const tokenData = JSON.parse(fs.readFileSync(filepath, 'utf8'));
    
    function processTokenGroup(obj, prefix = '') {
      Object.keys(obj).forEach(key => {
        if (typeof obj[key] === 'object' && obj[key] !== null) {
          if (obj[key].light && obj[key].dark) {
            // Theme-aware token
            const varName = `--${prefix}${key}`.replace(/\./g, '-');
            lightThemeContent += `  ${varName}: ${obj[key].light};\n`;
            darkThemeContent += `  ${varName}: ${obj[key].dark};\n`;
            mediaQueryContent += `    ${varName}: ${obj[key].dark};\n`;
          } else if (obj[key].value) {
            // Standard token
            const varName = `--${prefix}${key}`.replace(/\./g, '-');
            cssContent += `  ${varName}: ${obj[key].value};\n`;
          } else if (!obj[key].description) {
            // Nested group
            processTokenGroup(obj[key], `${prefix}${key}-`);
          }
        }
      });
    }
    
    processTokenGroup(tokenData);
  });
  
  cssContent += '}\n\n';
  lightThemeContent += '}\n\n';
  darkThemeContent += '}\n\n';
  mediaQueryContent += '  }\n}\n\n';
  
  // Combine all CSS
  const finalCss = cssContent + lightThemeContent + darkThemeContent + mediaQueryContent;
  
  // Write the enhanced tokens CSS
  fs.writeFileSync(path.join(config.distDir, 'tokens.css'), finalCss);
  
  return finalCss;
}

try {
  const processedTokens = processThemeTokens();
  console.log('✅ Theme-aware tokens processed successfully');
} catch (error) {
  console.error('❌ Theme token processing failed:', error.message);
  
  // Fallback to standard Style Dictionary
  console.log('📋 Falling back to standard token processing...');
  const configPath = path.join(__dirname, 'style-dictionary-temp.json');
  fs.writeFileSync(configPath, JSON.stringify(styleDictionaryConfig, null, 2));
  
  try {
    execSync(`npx style-dictionary build --config ${configPath}`, { 
      stdio: 'inherit',
      cwd: __dirname 
    });
    console.log('✅ Standard tokens processed successfully');
  } finally {
    if (fs.existsSync(configPath)) {
      fs.unlinkSync(configPath);
    }
  }
}

// Step 2: Create main SCSS file that imports everything
const mainScssContent = `
// dataimago Design System - Main Entry Point
// Generated by build.js - do not edit directly

// Import design tokens (SCSS source)
@import 'tokens';

// Base styles using design tokens  
@import 'styles/base';
@import 'styles/components';
@import 'styles/utilities';
@import 'styles/accessibility';
`;

const mainScssPath = path.join(config.srcDir, 'main.scss');
fs.writeFileSync(mainScssPath, mainScssContent);

// Step 3: Compile SCSS to CSS (both main and website theme)
console.log('🎨 Compiling SCSS...');

// Compile main design system
try {
  const sassCmd = `npx sass ${mainScssPath}:${path.join(config.distDir, 'dataimago.css')} --style=expanded --source-map`;
  execSync(sassCmd, { stdio: 'inherit', cwd: __dirname });
  console.log('✅ Main design system compiled successfully');
} catch (error) {
  console.error('❌ Main SCSS compilation failed:', error.message);
  process.exit(1);
}

// Compile website theme
try {
  const websiteThemePath = path.join(config.stylesDir, 'website-theme.scss');
  
  if (fs.existsSync(websiteThemePath)) {
    // Compile unified website theme
    const websiteCmd = `npx sass ${websiteThemePath}:${path.join(config.distDir, 'website-theme.css')} --style=expanded --source-map`;
    execSync(websiteCmd, { stdio: 'inherit', cwd: __dirname });
    console.log('✅ Website theme compiled successfully');
    
    // BULLETPROOF BUILD: Auto-generate self-contained theme files from modular sources
    console.log('🏗️ Generating self-contained theme files from modular sources...');
    
    // Read modular source files (single source of truth)
    const tokensPath = path.join(config.distDir, 'tokens.css');
    const themeVariablesPath = path.join(config.srcDir, 'styles', 'themes', 'theme-variables.scss');
    const sharedComponentsPath = path.join(config.srcDir, 'styles', 'themes', 'shared-components.scss');
    const websiteFeaturesPath = path.join(config.srcDir, 'styles', 'themes', 'website-features.scss');
    
    // Read all modular content
    const tokensContent = fs.existsSync(tokensPath) ? fs.readFileSync(tokensPath, 'utf8') : '';
    const themeVariablesContent = fs.existsSync(themeVariablesPath) ? fs.readFileSync(themeVariablesPath, 'utf8') : '';
    const sharedComponentsContent = fs.existsSync(sharedComponentsPath) ? fs.readFileSync(sharedComponentsPath, 'utf8') : '';
    const websiteFeaturesContent = fs.existsSync(websiteFeaturesPath) ? fs.readFileSync(websiteFeaturesPath, 'utf8') : '';
    
    // Generate self-contained light theme
    const lightContent = `// dataimago Website Light Theme - Auto-generated from modular sources
// This file is self-contained for Quarto compatibility
// Source of truth: ui/src/styles/themes/ (modular files)

/*-- scss:defaults --*/
$h2-font-size: 1.6rem !default;
$headings-font-weight: 500 !default;
$body-bg: rgb(237, 237, 235) !default;
$btn-code-copy-color: #7c7c7c !default;
$btn-code-copy-color-active: #000 !default;

/*-- scss:rules --*/
// === DESIGN TOKENS (from tokens.scss) ===
${tokensContent.replace(/\/\/ .*$/gm, '').replace(/^\s*$/gm, '').trim()}

// === LIGHT THEME VARIABLES ===
:root {
  --theme-body-bg: rgb(237, 237, 235);
  --theme-navbar-bg: rgb(237, 237, 235);
  --theme-navbar-bg-scrolled: rgb(237, 237, 238);
  --theme-body-bg-scrolled: rgb(237, 237, 238);
  --theme-text-primary: #000000;
  --theme-text-secondary: #7c7c7c;
  --theme-text-hover: #000000;
  --theme-dropdown-bg: rgb(225, 225, 223);
  --theme-dropdown-border: rgb(220, 220, 218);
  --theme-dropdown-hover-bg: rgb(237, 237, 235);
  --theme-dropdown-hover-shadow: rgba(220, 220, 218, 0.8);
}

// === SHARED COMPONENTS (from shared-components.scss) ===
${sharedComponentsContent.replace(/\/\/ .*$/gm, '').replace(/^\s*$/gm, '').trim()}

// === WEBSITE FEATURES (from website-features.scss) ===
${websiteFeaturesContent.replace(/\/\/ .*$/gm, '').replace(/^\s*$/gm, '').trim()}`;

    // Generate self-contained dark theme
    const darkContent = `// dataimago Website Dark Theme - Auto-generated from modular sources
// This file is self-contained for Quarto compatibility
// Source of truth: ui/src/styles/themes/ (modular files)

/*-- scss:defaults --*/
$h2-font-size: 1.6rem !default;
$headings-font-weight: 500 !default;
$body-bg: rgb(20, 20, 16) !default;
$btn-code-copy-color: #7c7c7c !default;
$btn-code-copy-color-active: rgb(237, 237, 235) !default;

/*-- scss:rules --*/
// === DESIGN TOKENS (from tokens.scss) ===
${tokensContent.replace(/\/\/ .*$/gm, '').replace(/^\s*$/gm, '').trim()}

// === DARK THEME VARIABLES ===
:root {
  --theme-body-bg: rgb(20, 20, 16);
  --theme-navbar-bg: rgb(20, 20, 16);
  --theme-navbar-bg-scrolled: rgb(20, 20, 22);
  --theme-body-bg-scrolled: rgb(20, 20, 22);
  --theme-text-primary: rgb(237, 237, 235);
  --theme-text-secondary: #83838f;
  --theme-text-hover: rgb(237, 237, 235);
  --theme-dropdown-bg: rgb(32, 32, 34);
  --theme-dropdown-border: rgb(37, 37, 39);
  --theme-dropdown-hover-bg: rgb(20, 20, 16);
  --theme-dropdown-hover-shadow: rgba(37, 37, 39, 0.8);
}

// === SHARED COMPONENTS (from shared-components.scss) ===
${sharedComponentsContent.replace(/\/\/ .*$/gm, '').replace(/^\s*$/gm, '').trim()}

// === WEBSITE FEATURES (from website-features.scss) ===
${websiteFeaturesContent.replace(/\/\/ .*$/gm, '').replace(/^\s*$/gm, '').trim()}`;

    // Write auto-generated self-contained files
    fs.writeFileSync(path.join(config.distDir, 'website-light.scss'), lightContent);
    fs.writeFileSync(path.join(config.distDir, 'website-dark.scss'), darkContent);
    
    console.log('✅ Light/Dark theme variants generated');
  } else {
    console.log('⚠️ Website theme not found, skipping...');
  }
} catch (error) {
  console.error('❌ Website theme compilation failed:', error.message);
  process.exit(1);
}

// Step 3.5: Compile page-specific SCSS files
console.log('📄 Compiling page-specific SCSS...');

const pagesDir = path.join(config.srcDir, 'pages');
let pageFilesCompiled = 0;

if (fs.existsSync(pagesDir)) {
  try {
    // Compile main page files
    const pageFiles = fs.readdirSync(pagesDir)
      .filter(file => file.endsWith('.scss') && !fs.statSync(path.join(pagesDir, file)).isDirectory());
    
    pageFiles.forEach(file => {
      const srcPath = path.join(pagesDir, file);
      const destPath = path.join(config.distDir, file.replace('.scss', '.css'));
      const sassCmd = `npx sass ${srcPath}:${destPath} --style=expanded --source-map`;
      execSync(sassCmd, { stdio: 'inherit', cwd: __dirname });
      pageFilesCompiled++;
    });
    
    // Compile shared components
    const sharedDir = path.join(pagesDir, 'shared');
    if (fs.existsSync(sharedDir)) {
      const sharedFiles = fs.readdirSync(sharedDir)
        .filter(file => file.endsWith('.scss'));
      
      sharedFiles.forEach(file => {
        const srcPath = path.join(sharedDir, file);
        const destPath = path.join(config.distDir, `shared-${file.replace('.scss', '.css')}`);
        const sassCmd = `npx sass ${srcPath}:${destPath} --style=expanded --source-map`;
        execSync(sassCmd, { stdio: 'inherit', cwd: __dirname });
        pageFilesCompiled++;
      });
    }
    
    if (pageFilesCompiled > 0) {
      console.log(`✅ Page-specific SCSS compiled successfully (${pageFilesCompiled} files)`);
    } else {
      console.log('⚠️ No page-specific SCSS files found');
    }
  } catch (error) {
    console.error('❌ Page-specific SCSS compilation failed:', error.message);
    process.exit(1);
  }
} else {
  console.log('⚠️ Pages directory not found, skipping page-specific compilation');
}

// Step 4: Run PostCSS for optimization
console.log('⚡ Running PostCSS optimization...');

// PostCSS configuration
const postcssConfig = {
  plugins: [
    require('autoprefixer'),
    require('cssnano')({
      preset: 'default'
    })
  ]
};

try {
  const postcssConfigPath = path.join(__dirname, 'postcss.config.js');
  fs.writeFileSync(postcssConfigPath, `module.exports = ${JSON.stringify(postcssConfig, null, 2)};`);
  
  const postcssCmd = `npx postcss ${path.join(config.distDir, 'dataimago.css')} -o ${path.join(config.distDir, 'dataimago.min.css')} --config ${postcssConfigPath}`;
  execSync(postcssCmd, { stdio: 'inherit', cwd: __dirname });
  
  console.log('✅ PostCSS optimization complete');
  
  // Clean up PostCSS config
  if (fs.existsSync(postcssConfigPath)) {
    fs.unlinkSync(postcssConfigPath);
  }
} catch (error) {
  console.error('❌ PostCSS optimization failed:', error.message);
  process.exit(1);
}

// Step 5: Generate Tailwind preset for Next.js integration
console.log('🌊 Generating Tailwind preset...');

const tailwindPreset = `
// dataimago Tailwind CSS Preset
// Generated by build.js - enables dataimago design system in Next.js apps

module.exports = {
  theme: {
    extend: {
      colors: {
        'di-primary': 'var(--color-brand-primary, #2C3E50)',
        'di-secondary': 'var(--color-brand-secondary, #34495E)', 
        'di-accent': 'var(--color-brand-accent, #3498DB)',
        'di-ethical': 'var(--color-brand-ethical, #E74C3C)'
      }
    }
  }
};
`;

fs.writeFileSync(path.join(config.distDir, 'tailwind-preset.js'), tailwindPreset);
console.log('✅ Tailwind preset generated');

// Step 6: Process JavaScript files
console.log('📜 Processing JavaScript files...');

// Create js distribution directory
const jsDist = path.join(config.distDir, 'js');
if (!fs.existsSync(jsDist)) {
  fs.mkdirSync(jsDist, { recursive: true });
}

// Process JavaScript files recursively (preserving directory structure)
function processJSFiles(srcDir, distDir, basePath = '') {
  if (!fs.existsSync(srcDir)) return 0;
  
  const items = fs.readdirSync(srcDir);
  let processedCount = 0;
  
  items.forEach(item => {
    const srcPath = path.join(srcDir, item);
    const stats = fs.statSync(srcPath);
    
    if (stats.isDirectory()) {
      // Create corresponding directory in dist
      const subDistDir = path.join(distDir, item);
      if (!fs.existsSync(subDistDir)) {
        fs.mkdirSync(subDistDir, { recursive: true });
      }
      
      // Recursively process subdirectory
      processedCount += processJSFiles(srcPath, subDistDir, path.join(basePath, item));
    } else if (item.endsWith('.js')) {
      // Process JavaScript file
      const distPath = path.join(distDir, item);
      const relativePath = path.join(basePath, item).replace(/\\/g, '/');
      
      const content = fs.readFileSync(srcPath, 'utf8');
      const processedContent = `/**
 * ${item} - dataimago Design System
 * Built: ${new Date().toISOString()}
 * Source: ui/src/js/${relativePath}
 */
${content}`;
      
      fs.writeFileSync(distPath, processedContent);
      processedCount++;
      
      // Log with appropriate path
      const stats = fs.statSync(distPath);
      const sizeKB = Math.round(stats.size / 1024 * 100) / 100;
      const displayPath = relativePath || item;
      console.log(`   ✓ js/${displayPath} (${sizeKB} KB)`);
    }
  });
  
  return processedCount;
}

const totalJSFiles = processJSFiles(config.jsDir, jsDist);

if (totalJSFiles > 0) {
  console.log(`✅ JavaScript files processed (${totalJSFiles} files)`);
} else {
  console.log('⚠️  No JavaScript source directory found (ui/src/js)');
}

// Step 7: Generate build manifest
const manifest = {
  name: 'dataimago Design System',
  version: '0.1.0', 
  buildTime: new Date().toISOString(),
  assets: {
    'tokens.css': 'CSS custom properties from design tokens',
    'dataimago.css': 'Expanded CSS for development',
    'dataimago.min.css': 'Minified CSS for production',
    'tailwind-preset.js': 'Tailwind CSS preset for Next.js integration'
  },
  javascript: {}
};

// Add JavaScript files to manifest
if (fs.existsSync(path.join(config.distDir, 'js'))) {
  const jsFiles = fs.readdirSync(path.join(config.distDir, 'js')).filter(file => file.endsWith('.js'));
  jsFiles.forEach(file => {
    manifest.javascript[`js/${file}`] = `JavaScript component: ${file.replace('.js', '')}`;
  });
}

// Add website theme files to manifest if they exist
if (fs.existsSync(path.join(config.distDir, 'website-theme.css'))) {
  manifest.assets['website-theme.css'] = 'Unified website theme (light/dark aware)';
  manifest.assets['website-light.scss'] = 'Quarto light theme compatibility';
  manifest.assets['website-dark.scss'] = 'Quarto dark theme compatibility';
}

fs.writeFileSync(
  path.join(config.distDir, 'manifest.json'), 
  JSON.stringify(manifest, null, 2)
);

// Step 8: Distribute assets to all channels
console.log('📦 Distributing assets to all channels...');

    // Collect all available files from dist directory
    const coreFiles = ['tokens.css', 'dataimago.css', 'dataimago.min.css', 'website-theme.css', 'website-light.scss', 'website-dark.scss'];
    const pageFiles = fs.existsSync(path.join(config.distDir))
      ? fs.readdirSync(config.distDir)
          .filter(file => (file.endsWith('.css') || file.endsWith('.scss')) && !coreFiles.includes(file))
      : [];
      
    // Note: Page files now use descriptive names:
    // - documentation.css (formerly r-package.css)  
    // - landing.css (formerly index.css)
    // - shared-enhanced-toc.css (unchanged)

const distributionChannels = [
  {
    name: 'CDN Assets (inst/quarto-assets/)',
    path: path.join(__dirname, '..', 'inst', 'quarto-assets'),
    files: ['tokens.css', 'dataimago.css', 'dataimago.min.css', 'website-theme.css', ...pageFiles.filter(f => f.endsWith('.css'))]
  },
  {
    name: 'Website Assets (ui/www/assets/css/)',
    path: path.join(__dirname, 'www', 'assets', 'css'),
    files: [...coreFiles, ...pageFiles]
  },
  {
    name: 'Quarto Extension (ui/www/_extensions/dataimago/ai-native/assets/css/)',
    path: path.join(__dirname, 'www', '_extensions', 'dataimago', 'ai-native', 'assets', 'css'),
    files: [...coreFiles, ...pageFiles]
  },
  {
    name: 'Docs Assets (docs/assets/css/)',
    path: path.join(__dirname, '..', 'docs', 'assets', 'css'),
    files: ['tokens.css', 'dataimago.css', 'dataimago.min.css', ...pageFiles.filter(f => f.endsWith('.css'))]
  }
];

distributionChannels.forEach(channel => {
  // Ensure target directory exists
  if (!fs.existsSync(channel.path)) {
    fs.mkdirSync(channel.path, { recursive: true });
  }

  let copied = 0;
  channel.files.forEach(file => {
    const srcPath = path.join(config.distDir, file);
    const destPath = path.join(channel.path, file);
    
    if (fs.existsSync(srcPath)) {
      fs.copyFileSync(srcPath, destPath);
      copied++;
    }
  });
  
  console.log(`   ✓ ${channel.name} (${copied}/${channel.files.length} files)`);
});

// Also distribute JavaScript assets
const jsChannels = [
  {
    name: 'Website JS (ui/www/assets/js/)',
    path: path.join(__dirname, 'www', 'assets', 'js')
  },
  {
    name: 'Extension JS (ui/www/_extensions/dataimago/ai-native/assets/js/)',
    path: path.join(__dirname, 'www', '_extensions', 'dataimago', 'ai-native', 'assets', 'js')
  },
  {
    name: 'Docs JS (docs/assets/js/)',
    path: path.join(__dirname, '..', 'docs', 'assets', 'js')
  }
];

// Enhanced JS distribution with directory structure preservation
function distributeJSFiles(srcDir, channels, basePath = '') {
  if (!fs.existsSync(srcDir)) return;
  
  const items = fs.readdirSync(srcDir);
  
  items.forEach(item => {
    const srcPath = path.join(srcDir, item);
    const stats = fs.statSync(srcPath);
    
    if (stats.isDirectory()) {
      // Create subdirectories in all channels and recurse
      channels.forEach(channel => {
        const channelSubDir = path.join(channel.path, item);
        if (!fs.existsSync(channelSubDir)) {
          fs.mkdirSync(channelSubDir, { recursive: true });
        }
      });
      
      distributeJSFiles(srcPath, channels.map(channel => ({
        ...channel,
        path: path.join(channel.path, item)
      })), path.join(basePath, item));
    } else if (item.endsWith('.js')) {
      // Distribute JS files
      channels.forEach(channel => {
        const destPath = path.join(channel.path, item);
        fs.copyFileSync(srcPath, destPath);
      });
    }
  });
}

if (fs.existsSync(path.join(config.distDir, 'js'))) {
  // Count total JS files for reporting
  function countJSFiles(dir) {
    let count = 0;
    const items = fs.readdirSync(dir);
    
    items.forEach(item => {
      const itemPath = path.join(dir, item);
      const stats = fs.statSync(itemPath);
      
      if (stats.isDirectory()) {
        count += countJSFiles(itemPath);
      } else if (item.endsWith('.js')) {
        count++;
      }
    });
    
    return count;
  }
  
  const totalJSFiles = countJSFiles(path.join(config.distDir, 'js'));
  
  jsChannels.forEach(channel => {
    if (!fs.existsSync(channel.path)) {
      fs.mkdirSync(channel.path, { recursive: true });
    }
  });
  
  // Distribute all JS files preserving directory structure
  distributeJSFiles(path.join(config.distDir, 'js'), jsChannels);
  
  jsChannels.forEach(channel => {
    console.log(`   ✓ ${channel.name} (${totalJSFiles} JS files)`);
  });
}

console.log('✅ Asset distribution complete');

// Clean up temporary files
if (fs.existsSync(mainScssPath)) {
  fs.unlinkSync(mainScssPath);
}

console.log('🎉 dataimago design system build complete!');
console.log(`📁 Assets generated in ${config.distDir}/`);

// List generated files
const files = fs.readdirSync(config.distDir);
files.forEach(file => {
  const filePath = path.join(config.distDir, file);
  const stats = fs.statSync(filePath);
  const sizeKB = Math.round(stats.size / 1024 * 100) / 100;
  console.log(`   ✓ ${file} (${sizeKB} KB)`);
});

console.log('🧠 Ethical AI design system ready for deployment!');