#' @importFrom fs dir_exists dir_create path file_exists
#' @importFrom glue glue
#' @importFrom jsonlite toJSON
#' @importFrom crayon green silver yellow red bold blue
NULL

# ============================================================================
# generate_mcp.R -- Generate MCP Tool Definitions from R Package Exports
# ============================================================================
#
# Creates Model Context Protocol (MCP) tool definitions from R function
# signatures and roxygen documentation. Enables AI agents to discover and
# invoke domain analyses programmatically.
#
# Pattern: roxygen docs -> JSON Schema -> MCP tool definitions
# Reference: dissertation-ai/mcp-schema.json (proof-of-concept)
# ============================================================================


#' Generate MCP Tool Definitions
#'
#' Reads exported functions from an R package and generates MCP-compatible
#' tool definitions as a JSON schema file. Each exported function becomes
#' a tool that AI agents can discover and invoke.
#'
#' @param pkg_path Character. Path to the R package source directory
#' @param output_path Character. Path for the generated mcp-schema.json file
#' @param pkg_name Character. Package name. If NULL, read from DESCRIPTION.
#' @param include_api_tools Logical. Include API server start/stop tools. Default: TRUE
#' @param verbose Logical. Print progress. Default: TRUE
#'
#' @return List with: files_created, tools_generated, tool_names
#'
#' @details
#' The generated MCP schema follows the Model Context Protocol specification:
#' - Each tool has a name, description, and inputSchema (JSON Schema)
#' - Parameter types are inferred from roxygen documentation and defaults
#' - Enum constraints are extracted from documented options
#' - Required parameters are identified from missing defaults
#'
#' The schema also includes:
#' - Resource descriptions (data, documentation, API spec)
#' - Capability declarations
#' - Integration metadata (framework, R package, frontend)
#'
#' @section AI Agent Integration:
#' Tools generated by this function enable AI agents to:
#' - Discover what analyses are available via the discovery tool
#' - Run specific analyses with validated parameters
#' - Access data variable metadata
#' - Start the REST API for interactive exploration
#'
#' @export
generate_mcp_tools <- function(pkg_path,
                               output_path,
                               pkg_name = NULL,
                               include_api_tools = TRUE,
                               verbose = TRUE) {
  # Read package name from DESCRIPTION if not provided
  if (is.null(pkg_name)) {
    desc_path <- fs::path(pkg_path, "DESCRIPTION")
    if (fs::file_exists(desc_path)) {
      desc_lines <- readLines(desc_path, warn = FALSE)
      pkg_line <- grep("^Package:", desc_lines, value = TRUE)
      if (length(pkg_line) > 0) {
        pkg_name <- trimws(sub("^Package:\\s*", "", pkg_line[1]))
      }
    }
    if (is.null(pkg_name)) {
      pkg_name <- basename(pkg_path)
    }
  }

  if (verbose) {
    ui_info(glue::glue("\U0001F916 Generating MCP tool definitions for '{pkg_name}'"))
  }

  # Parse exported functions
  exports <- parse_roxygen_exports(pkg_path, verbose = verbose)

  if (length(exports) == 0) {
    if (verbose) ui_warn("No exported functions found -- MCP schema will be minimal")
  }

  # Build tool definitions

  tools <- list()

  for (fn_name in names(exports)) {
    fn_meta <- exports[[fn_name]]
    tool <- build_mcp_tool(fn_name, fn_meta, pkg_name)
    tools <- c(tools, list(tool))
  }

  # Add API server tool if requested
  if (include_api_tools) {
    tools <- c(tools, list(build_api_start_tool(pkg_name)))
  }

  # Build full schema
  schema <- list(
    name = glue::glue("{pkg_name}-mcp-tools"),
    version = "1.0.0",
    description = glue::glue(
      "Model Context Protocol tools for the {pkg_name} R package ",
      "-- auto-generated by dataimago"
    ),
    tools = tools,
    resources = build_mcp_resources(pkg_name, pkg_path),
    capabilities = build_mcp_capabilities(exports),
    integration = list(
      framework = "dataimago",
      r_package = pkg_name,
      frontend = "NextJS 14",
      documentation = "Quarto"
    )
  )

  # Write schema
  output_dir <- dirname(output_path)
  if (!fs::dir_exists(output_dir)) {
    fs::dir_create(output_dir, recurse = TRUE)
  }

  json_content <- jsonlite::toJSON(schema, auto_unbox = TRUE, pretty = TRUE)
  writeLines(json_content, output_path)

  results <- list(
    files_created = output_path,
    tools_generated = length(tools),
    tool_names = vapply(tools, function(t) t$name, character(1))
  )

  if (verbose) {
    ui_done(glue::glue("Generated MCP schema with {length(tools)} tools"))
    for (tool in tools) {
      ui_info(glue::glue("  \U0001F527 {tool$name}: {substr(tool$description, 1, 60)}..."))
    }
  }

  invisible(results)
}


# ============================================================================
# Internal: MCP Tool Building
# ============================================================================

#' Build a single MCP tool definition from function metadata
#' @noRd
build_mcp_tool <- function(fn_name, fn_meta, pkg_name) {
  # Tool name: package_functionName -> snake_case
  tool_name <- paste0(pkg_name, "_", fn_to_endpoint(fn_name))
  tool_name <- gsub("-", "_", tool_name)

  # Build input schema
  properties <- list()
  required <- character(0)

  for (param_name in names(fn_meta$params)) {
    p <- fn_meta$params[[param_name]]
    prop <- list(
      type = r_type_to_json_schema(p$type),
      description = p$description
    )

    # Add default
    if (!is.null(p$default) && !is.na(p$default)) {
      prop[["default"]] <- coerce_default_value(p$default, p$type)
    }

    # Add enum
    if (!is.null(p$enum) && length(p$enum) > 0) {
      prop[["enum"]] <- as.list(p$enum)
    }

    # Add integer constraints
    if (p$type == "integer") {
      if (grepl("port", param_name, ignore.case = TRUE)) {
        prop[["minimum"]] <- 1024
        prop[["maximum"]] <- 65535
      }
    }

    properties[[param_name]] <- prop

    if (isTRUE(p$required)) {
      required <- c(required, param_name)
    }
  }

  input_schema <- list(
    type = "object",
    properties = properties,
    additionalProperties = FALSE
  )

  if (length(required) > 0) {
    input_schema[["required"]] <- as.list(required)
  }

  # Phase 2e: the canonical public surface for invoking this tool is the
  # NextJS API route tree, not the R function directly. `implementation.endpoint`
  # records where to call it; `implementation.producer` is an optional hint to
  # the server (default: "default", i.e. whichever producer DATAIMAGO_PRODUCER
  # selects). MCP runtimes should treat these fields as the source of truth.
  endpoint_path <- paste0("/api/data/", fn_to_endpoint(fn_name))

  list(
    name = tool_name,
    description = paste0(fn_meta$title, ". ", fn_meta$description),
    inputSchema = input_schema,
    implementation = list(
      type = "nextjs_api",
      endpoint = endpoint_path,
      method = "GET",
      producer = "default",
      r_function = fn_name,
      r_package = pkg_name,
      description = glue::glue(
        "GET {endpoint_path} -- dispatched server-side to {pkg_name}::{fn_name}() ",
        "via the active producer driver."
      )
    )
  )
}


#' Build API server start tool
#' @noRd
build_api_start_tool <- function(pkg_name) {
  list(
    name = paste0(pkg_name, "_api_start"),
    description = glue::glue(
      "Start the {pkg_name} REST API server for local development ",
      "and web application integration."
    ),
    inputSchema = list(
      type = "object",
      properties = list(
        port = list(
          type = "integer",
          description = "Port number for the API server",
          default = 8000L,
          minimum = 1024L,
          maximum = 65535L
        ),
        host = list(
          type = "string",
          description = "Host address for the API server",
          default = "127.0.0.1"
        )
      ),
      additionalProperties = FALSE
    ),
    # The API-start tool is intentionally *not* an HTTP endpoint — it boots
    # the backing live-producer server. Flag `producer = "live"` so MCP
    # runtimes understand this tool only makes sense when the active
    # producer is the live driver.
    implementation = list(
      type = "r_function",
      producer = "live",
      r_function = glue::glue("run_{pkg_name}_api"),
      r_package = pkg_name,
      description = glue::glue(
        "Calls {pkg_name}::run_{pkg_name}_api() to start the live producer's ",
        "backing REST server."
      ),
      warning = "This starts a persistent server process."
    )
  )
}


#' Build MCP resources section
#' @noRd
build_mcp_resources <- function(pkg_name, pkg_path) {
  resources <- list(
    list(
      name = "package_documentation",
      description = "R package documentation generated by roxygen2",
      path = glue::glue("man/")
    ),
    list(
      name = "api_openapi_spec",
      description = "OpenAPI 3.0 specification for the REST API",
      uri = "http://localhost:8000/openapi.json"
    )
  )

  # Check for data directory
  data_dir <- fs::path(pkg_path, "data")
  if (fs::dir_exists(data_dir)) {
    rda_files <- list.files(data_dir, pattern = "\\.rda$|\\.RData$", full.names = FALSE)
    for (f in rda_files) {
      ds_name <- sub("\\.(rda|RData)$", "", f)
      resources <- c(resources, list(list(
        name = ds_name,
        description = glue::glue("Dataset: {ds_name}"),
        path = glue::glue("data/{f}")
      )))
    }
  }

  resources
}


#' Build MCP capabilities section
#' @noRd
build_mcp_capabilities <- function(exports) {
  list(
    data_access = list(
      read = TRUE,
      query = TRUE,
      filter = TRUE,
      aggregate = TRUE
    ),
    analysis = list(
      functions_available = length(exports),
      custom_analyses = TRUE
    ),
    api_services = list(
      rest_api = TRUE,
      openapi_spec = TRUE,
      cors_enabled = TRUE
    )
  )
}


# ============================================================================
# Internal: Type Conversion Helpers
# ============================================================================

#' Convert R type string to JSON Schema type
#' @noRd
r_type_to_json_schema <- function(r_type) {
  switch(r_type,
    "boolean" = "boolean",
    "integer" = "integer",
    "number" = "number",
    "numeric" = "number",
    "array" = "array",
    "list" = "object",
    "string" # default
  )
}


#' Coerce a default value string to the appropriate JSON type
#' @noRd
coerce_default_value <- function(default_str, type) {
  default_str <- gsub('^"|"$', "", as.character(default_str))

  switch(type,
    "boolean" = {
      if (tolower(default_str) %in% c("true", "t")) {
        TRUE
      } else if (tolower(default_str) %in% c("false", "f")) {
        FALSE
      } else {
        default_str
      }
    },
    "integer" = {
      val <- suppressWarnings(as.integer(gsub("L$", "", default_str)))
      if (is.na(val)) default_str else val
    },
    "number" = {
      val <- suppressWarnings(as.numeric(default_str))
      if (is.na(val)) default_str else val
    },
    default_str
  )
}
