#' @importFrom fs dir_exists path file_exists
#' @importFrom glue glue
#' @importFrom crayon green silver yellow red bold blue
NULL

#' Generate Project-Specific CLAUDE.md
#'
#' Creates a CLAUDE.md file for the generated project that provides
#' AI development context, references the dataimago knowledge wiki,
#' and includes domain-specific context from the source R package.
#'
#' This is part of Phase D (Recursive Loop) of the dataimago meta-tool
#' architecture: generated applications inherit AI-assisted development
#' context from the framework that produced them.
#'
#' @param project_path Character. Root directory of the generated project
#' @param project_name Character. Name of the project
#' @param source_pkg Character. Path to the source R package (NULL if scaffolding only)
#' @param framework Character. Target framework: "quarto", "shiny", "nextjs", or "full"
#' @param features Character vector. AI features included
#' @param verbose Logical. Print progress. Default: TRUE
#'
#' @return List with file path and content summary
#'
#' @keywords internal
generate_claude_md <- function(project_path,
                               project_name,
                               source_pkg = NULL,
                               framework = "quarto",
                               features = NULL,
                               verbose = TRUE) {
  if (verbose) ui_info("Generating project CLAUDE.md...")

  # Build sections
  sections <- list()

  # Header
  sections$header <- glue::glue(
    "# {project_name} \u2014 Development Context\n",
    "\n",
    "This project was generated by [dataimago](https://github.com/dataimago),\n",
    "an AI-native meta-tool framework that transforms R analysis packages\n",
    "into interactive web applications.\n"
  )

  # Architecture section
  sections$architecture <- build_architecture_section(framework, source_pkg)

  # Source package context
  if (!is.null(source_pkg)) {
    sections$source_pkg <- build_source_pkg_section(source_pkg, verbose)
  }

  # Key patterns
  sections$patterns <- build_patterns_section(framework)

  # Features context
  if (!is.null(features)) {
    sections$features <- build_features_section(features)
  }

  # Conventions
  sections$conventions <- build_conventions_section(framework)

  # Ethical framework
  sections$ethics <- paste0(
    "## Ethical Framework\n\n",
    "This project inherits dataimago's ethical constraints structurally:\n\n",
    "- **Contrast enforcement**: All color combinations meet WCAG 2.1 AA (7.0:1 minimum)\n",
    "- **Motion dignity**: Animations capped at 300ms, `prefers-reduced-motion` honored\n",
    "- **Bundle budgets**: Performance equity enforced via file size limits\n",
    "- **Accessibility**: All components must be keyboard-navigable with ARIA labels\n",
    "- **Data privacy**: No user data collection without explicit consent\n\n",
    "These constraints are not optional \u2014 they propagate from the design system\n",
    "through the build pipeline and CI checks.\n"
  )

  # Environment variables
  if (framework %in% c("nextjs", "full")) {
    sections$env <- paste0(
      "## Environment Variables\n\n",
      "```bash\n",
      "NEXT_PUBLIC_API_MODE=static    # 'live' or 'static'\n",
      "NEXT_PUBLIC_API_URL=http://localhost:8000  # R API server URL\n",
      "```\n"
    )
  }

  # Assemble the full document
  content <- paste(unlist(sections), collapse = "\n---\n\n")

  # Write the file
  claude_md_path <- fs::path(project_path, "CLAUDE.md")
  writeLines(content, claude_md_path)

  if (verbose) ui_done("Generated CLAUDE.md with project context")

  invisible(list(
    file = claude_md_path,
    sections = names(sections)
  ))
}


# ====================================================================
# Helper functions for building CLAUDE.md sections
# ====================================================================

build_architecture_section <- function(framework, source_pkg) {
  base <- paste0(
    "## Architecture\n\n",
    "**Framework:** ", framework, "\n"
  )

  if (!is.null(source_pkg)) {
    base <- paste0(
      base,
      "**Pipeline:** R functions \u2192 REST API \u2192 MCP Tools \u2192 TypeScript \u2192 Web UI\n\n",
      "The source R package is the single source of truth. All API endpoints,\n",
      "MCP tool definitions, TypeScript types, and the API client are derived\n",
      "from the R package's exported functions and roxygen documentation.\n"
    )
  } else {
    base <- paste0(
      base,
      "\nThis is a scaffolded project without a source R package.\n",
      "Add a source package to enable the full meta-tool pipeline.\n"
    )
  }

  base
}

build_source_pkg_section <- function(source_pkg, verbose) {
  section <- "## Source R Package\n\n"

  # Try to extract package info
  desc_path <- fs::path(source_pkg, "DESCRIPTION")
  if (fs::file_exists(desc_path)) {
    desc_lines <- readLines(desc_path)
    pkg_line <- grep("^Package:", desc_lines, value = TRUE)
    title_line <- grep("^Title:", desc_lines, value = TRUE)
    desc_line <- grep("^Description:", desc_lines, value = TRUE)

    if (length(pkg_line) > 0) {
      pkg_name <- trimws(sub("^Package:\\s*", "", pkg_line[1]))
      section <- paste0(section, "**Package:** `", pkg_name, "`\n")
    }
    if (length(title_line) > 0) {
      title <- trimws(sub("^Title:\\s*", "", title_line[1]))
      section <- paste0(section, "**Title:** ", title, "\n")
    }
    if (length(desc_line) > 0) {
      desc <- trimws(sub("^Description:\\s*", "", desc_line[1]))
      section <- paste0(section, "**Description:** ", desc, "\n")
    }
  }

  # List exported functions
  tryCatch(
    {
      exports <- parse_roxygen_exports(source_pkg, verbose = FALSE)
      if (length(exports) > 0) {
        fn_names <- vapply(exports, function(x) x$name, character(1))
        section <- paste0(section, "\n**Exported functions:**\n")
        for (fn in fn_names) {
          fn_meta <- exports[[which(fn_names == fn)]]
          desc <- if (!is.null(fn_meta$title)) fn_meta$title else ""
          section <- paste0(section, "- `", fn, "()` \u2014 ", desc, "\n")
        }
      }
    },
    error = function(e) {
      if (verbose) ui_warn(glue::glue("Could not parse exports: {e$message}"))
    }
  )

  section
}

build_patterns_section <- function(framework) {
  section <- "## Key Patterns\n\n"

  if (framework %in% c("nextjs", "full")) {
    section <- paste0(
      section,
      "### Dual-Mode API Client\n",
      "The `@dataimago/shared-utils` package provides a client that switches between:\n",
      "- **Live mode** (`NEXT_PUBLIC_API_MODE=live`): HTTP requests to R API server\n",
      "- **Static mode** (`NEXT_PUBLIC_API_MODE=static`): Reads pre-computed JSON from `public/api/`\n\n",
      "### MCP Tool Integration\n",
      "AI agents interact with this application through MCP tools defined in `mcp-schema.json`.\n",
      "The `@dataimago/mcp-tools` package validates parameters and routes calls through the API client.\n\n",
      "### Domain-Agnostic Data Explorer\n",
      "The data explorer reads available endpoints from the discovery API rather than\n",
      "hardcoding domain knowledge. It works with any R package's exported functions.\n"
    )
  } else if (framework == "quarto") {
    section <- paste0(
      section,
      "### Multi-Format Output\n",
      "Quarto renders content to multiple formats (HTML, PDF, DOCX) from single .qmd sources.\n",
      "The dataimago design system tokens are applied via the Quarto extension.\n"
    )
  } else if (framework == "shiny") {
    section <- paste0(
      section,
      "### Reactive R Integration\n",
      "Shiny apps run R analysis functions reactively in the server.\n",
      "The dataimago design system is applied via bslib theming.\n"
    )
  }

  section
}

build_features_section <- function(features) {
  section <- "## AI Features\n\n"

  feature_descriptions <- list(
    "chat-interface" = "AI chat interface for conversational data exploration",
    "document-analysis" = "Document processing, extraction, and summarization",
    "data-viz" = "Interactive data visualizations (D3.js / Recharts)",
    "streaming" = "Real-time streaming interfaces for live data",
    "model-management" = "AI model selection and performance monitoring"
  )

  for (f in features) {
    desc <- feature_descriptions[[f]]
    if (is.null(desc)) desc <- f
    section <- paste0(section, "- **", f, "**: ", desc, "\n")
  }

  section
}

build_conventions_section <- function(framework) {
  section <- "## Conventions\n\n"

  if (framework %in% c("nextjs", "full")) {
    section <- paste0(
      section,
      "- TypeScript strict mode everywhere\n",
      "- React components use `'use client'` when they need interactivity\n",
      "- SWR hooks for data fetching in client components\n",
      "- Tailwind CSS with dataimago color palette\n",
      "- All components must be accessible (WCAG 2.1 AA)\n",
      "- File naming: components `kebab-case.tsx`, hooks `useCase.ts`\n"
    )
  } else if (framework == "quarto") {
    section <- paste0(
      section,
      "- Quarto .qmd files for all content\n",
      "- YAML frontmatter for metadata\n",
      "- Cross-references with `@fig-`, `@tbl-`, `@sec-` prefixes\n",
      "- dataimago Quarto extension for theming\n"
    )
  } else if (framework == "shiny") {
    section <- paste0(
      section,
      "- bslib for theming with dataimago tokens\n",
      "- Module pattern for complex UI components\n",
      "- Reactive programming for data flow\n"
    )
  }

  section
}
